### PR TITLE
devTasks

### PR DESCRIPTION
**Pull request by ManuelHentschel**
This PR removes two compiled .js files (keeping only their source .ts files) and updates the vscode tasks so that they generate those files for debugging/compilation.

### CODE REVIEW

**Review by renkun-ken — APPROVED** [review]
LGTM

**Comment by renkun-ken** [comment]
The following files are generates as untracked:

```
html/help/script.js
html/httpgd/index.js
```

@ManuelHentschel Maybe we should ignore these files in a gitignore?

**Comment by ManuelHentschel** [comment]
> The following files are generates as untracked each time I debug the extension:
> 
> ```
> html/help/script.js
> html/httpgd/index.js
> ```
> 
> @ManuelHentschel Maybe we should ignore these files in a gitignore?

Done in https://github.com/REditorSupport/vscode-R/commit/7ddd0d55129ac5007de348923b217877320fca44

**Comment by renkun-ken** [comment]
Seems `html/session/webview/observer.js` is ignored too. Not sure if it should be?

**Comment by ManuelHentschel** [comment]
> Seems `html/session/webview/observer.js` is ignored too. Not sure if it should be?

Files that are already tracked (like `observer.js`) shouldn't be affected by new .gitignore entries. You can check that e.g. by modifying the file and running `git status` (which correctly shows `observer.js` for me).

**Comment by renkun-ken** [comment]
OK. Thanks for reminding!

**Pull request merged**
