### PR TITLE
Bump @types/vscode from 1.57.0 to 1.60.0

### PR DESCRIPTION
**Pull request by ElianHugh**
Updates the type definitions for vscode. I'm not sure where to obtain the changelog from!

---

I thought this was automated, but while looking into vscode's new features I was getting type errors.

### CODE REVIEW

**Comment by renkun-ken** [comment]
Looks like something should be fixed.

**Review by renkun-ken — APPROVED** [review]
LGTM

**Comment by renkun-ken** [comment]
I'm about to make a new release, but I find the version in `package.json` is still `1.57.0` at 

https://github.com/REditorSupport/vscode-R/blob/c0e75b2b36c79a939a6b323f5dcde7d688b609be/package.json#L29

and

https://github.com/REditorSupport/vscode-R/blob/c0e75b2b36c79a939a6b323f5dcde7d688b609be/package.json#L1672

Should we also update the version here?

**Comment by ElianHugh** [comment]
Sorry, I lost track of this! I think it's probably safe to update, given we tend to look into new features?

**Pull request merged**
